### ISSUE TITLE
Specifying composer version in README.md

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#12]
Hey @zaantar, I forgot to mention this sooner: the first time I tried to build the plugin, it didn't work. The reason it failed was that I was using the latest version of composer, 2.x, and the plugin needs to be built with the older 1.x version. The `README.md` file, however, doesn't mention a version. Should I submit a PR with an update to `README.md` that explicitly states the version number?

**Comment by zaantar** [comment]
Sure, go ahead, please! I was not aware of this limitation

**Comment by baizmandesign** [comment]
@zaantar Will do. Should I also open another issue about creating support for composer 2.x?

**Comment by zaantar** [comment]
Yes, please. :)

Generally speaking, you can open an issue without asking, the worst it can happen is that it will be closed as a wontfix

**Comment by baizmandesign** [comment]
@zaantar OK, sounds good!
