### ISSUE TITLE
Update compatibility of Composer from version 1.x to the latest version, 2.x

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#14]
The plugin cannot be built against the latest version of Composer, 2.x. It only builds against 1.x.

When I have a couple minutes, I'll try to provide more details about the error I encountered when I attempted to build the plugin against 2.x.

**Comment by baizmandesign** [comment]
Note: it may be desirable to decide which version of Composer to build against before handling #11.

**Comment by baizmandesign** [comment]
Following the Composer installation instructions on https://getcomposer.org/download/:

```
$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
$ php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
$ php composer-setup.php
$ php -r "unlink('composer-setup.php');"
```

Output after `php composer-setup.php`:

```
All settings correct for using Composer
Downloading...

Composer (version 2.0.9) successfully installed to: /Users/saul/Desktop/toolset-cli-master/composer.phar
Use it: php composer.phar
```

(Note: this installs Composer in the current directory only.)

Then, following the instructions in `toolset-cli/README.md` to install the plugin:
```
$ php composer.phar install
```

Here is the output from the shell:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.6.2 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

I'm also attaching a screenshot from Terminal.

![Screen Shot 2021-02-17 at 20 58 58](https://user-images.githubusercontent.com/64377184/108294073-21574300-7163-11eb-82cf-34e0431a01a0.png)

**Comment by zaantar** [comment]
@baizmandesign, this is unfortunate but expected. We keep using composer v1 at OTGS for the moment, as switching to v2 is a much bigger task that needs to be planned and executed in a proper manner. To make things a bit easier, I played with GitHub Actions and there's now a job that builds the Toolset CLI plugin package for every commit to the `master` branch. Perhaps that will help. But I am afraid there's nothing I can do to make things work with Composer v2 at the moment. Perhaps something like [this](https://joostvanveen.com/a-40/run-composer-1-and-2-simultaniously) could be useful if you also need to have v2 installed on your computer. But I am closing this issue as a wontfix, we'll make the switch when our entire infrastructure is ready for it. Thanks for understanding.

**Comment by baizmandesign** [comment]
@zaantar Closing this issue is fine! It was more of an FYI than anything else. The important thing is that the composer version is clearly stated in the documentation now, so if someone does try to build the plugin themselves—which shouldn't be necessary now that you've implemented the automatic build via GitHub Actions—they won't fall into the version trap I did. :-)
