### ISSUE TITLE
Notification of updates in the WP dashboard

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#15]
It would be nice to be able to update the plugin automatically via the WP dashboard when a new version is released, as many other plugins can be (including the Toolset suite).

**Comment by zaantar** [comment]
@baizmandesign Should be totally doable, nice idea :) 

For example, [this](https://www.smashingmagazine.com/2015/08/deploy-wordpress-plugins-with-github-using-transients/) could be one way to achieve that (the article is a bit old, I just did a very fast search, there may be better sources). 

That being said, I am afraid we don't really have the manpower for this nice-to-have feature at the moment. But if you (or anyone else) feel like playing with this, you're more than welcome.

**Comment by baizmandesign** [comment]
@zaantar Can you assign this issue to me? I'd like to take a crack at it based on the link you provided.
