### ISSUE TITLE
Remove version number from asset names in releases

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#19]
There's a nifty [magic URL](https://docs.github.com/en/github/administering-a-repository/linking-to-releases) to download the latest version of a GitHub release asset:

https://github.com/user/repo/releases/latest/download/asset-name.zip

However, the `asset-name.zip` for toolset-cli includes the version number in it:

`toolset-cli-refs.tags.1.1.zip`

The unfortunate consequence of this is that one must know the version number to take advantage of the magic URL.

Could the version number be removed? The end result would be something like this:

https://github.com/OnTheGoSystems/toolset-cli/releases/latest/download/toolset-cli.zip

If removal isn't an option, I certainly understand why it would be desirable to keep the version number in the filename. (Another option might be to create two assets, one with the version number and one without it. But this redundancy seems a bit much.)

**Comment by zaantar** [comment]
@baizmandesign, honestly, I would prefer to keep the version number, to prevent any sort of confusion when working with the plugin ZIP files. AFAIK, this is also standard practice. Is there a particular use case where you'd find this helpful?

If you need to install Toolset CLI programmatically, you can still do it via `git clone ... && cd toolset-cli && composer install`.

**Comment by baizmandesign** [comment]
@zaantar That totally makes to me. The programmatic use case I was imagining looked like this...

```shell
$ wp plugin install --activate plugin1 plugin2 https://somesite.com/plugin3.zip https://github.com/OnTheGoSystems/toolset-cli/releases/latest/download/toolset-cli.zip
```

Basically, I'm seeking the ability to install the toolset-cli plugin via WP CLI (without knowing the current version).

To me this is a GitHub problem. As you said, and as most developers know, including the version number in the asset is standard. Here it has the unfortunate side effect of rendering the nifty magic URLs useless in practice.

Feel free to close this issue. :-) Thanks again, Jan!

**Comment by zaantar** [comment]
@baizmandesign I see. Well, for your use case, there are workarounds available, some [elegant but more complicated](https://www.rarst.net/code/link-latest-github-release-binary/), but some also very simple if you can rely on stuff like `curl` or `jq`, like [this comment](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2724872).

For Toolset CLI, specifically, you can do just:

```sh
wp plugin install --activate `curl -sL https://api.github.com/repos/OnTheGoSystems/toolset-cli/releases/latest | jq -r '.assets[].browser_download_url'`
```

and it should always give you the asset from the latest release.

Potential weak points:

- `curl` and `jq` is required
- I have no idea how this would work under Windows (unless you're using WSL, git-bash or some other cygwin-based environment)
- Unpredicted behavior if Toolset CLI starts producing multiple assets per release, but we have no plans for that whatsoever.

I hope this will make your work easier, but as you pointed out, this is rather a GitHub-related problem, so I'm closing this issue. :)
