### ISSUE TITLE
List relationships between posts?

### ISSUE THREAD

**Issue by jpl166** [OnTheGoSystems/toolset-cli#23]
I have a couple custom post types (chapter and member) and a one-to-many relationship defined for those types.  From the Web UI I can go to a "chapter" and see the list of "members" associated with it via that relationship.  I would really love a way to do that same thing from toolset-cli, so I can grab a list of all of the members associated with a chapter and then can script doing operations on them.  Does such a thing exist already in here and I haven't figured it out via the documentation, or would this be new code?

Thanks for any assistance!

**Comment by zaantar** [comment]
Hi, Toolset CLI currently supports manipulation with only _definitions_ of post relationships (except for the [wp types association](https://github.com/OnTheGoSystems/toolset-cli/blob/master/docs/types/association.md) command) and, unfortunately, we don't support querying of actual connections between posts (=associations) at the moment.

However, if you are familiar with PHP, you can use directly the [Post Relationship API](https://toolset.com/documentation/customizing-sites-using-php/post-relationships-api/) that is available directly from Toolset Types.

If you happen to implement it as a WP CLI command, we will be happy to include it in Toolset CLI as well.

I hope this helps.

**Comment by baizmandesign** [comment]
@jpl166 I'm a big fan of Toolset and use it in nearly all of my clients' websites. At the risk of sounding tacky, if this would be of value to you, I'd be happy to build the WP CLI command with the desired functionality for a fee. Please contact me at hello@baizmandesign.com.

**Comment by zaantar** [comment]
Handled by https://github.com/OnTheGoSystems/toolset-cli/pull/24.

**Comment by baizmandesign** [comment]
Hey, @jpl166. I felt a little slimy propositioning you earlier about creating this command, so I went ahead and made it. It's now merged with the production codebase. Enjoy!

**Comment by jpl166** [comment]
I wasn't quite certain how to respond, either, so I understand.  I'm also now looking at your pull and considering what further features would be potentially useful, and I've checked out your site and we might be in touch...

**Comment by baizmandesign** [comment]
@jpl166 Sounds great!
