### ISSUE TITLE
Add ZIP file format support to views import / export commands

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#5]
The web interface can import and export XML (\*.xml) and zipped XML (\*.zip) files. Currently, the CLI interface only supports XML.

**Comment by baizmandesign** [comment]
This issue can be assigned to me, and per discussion with @zaantar, I will take care of it after PRs #2, #3, and #4 are merged into the master branch.

**Comment by baizmandesign** [comment]
@zaantar I've added ZIP format support to the views export command, and it appears that two files are present in the ZIP archive: an XML file with the settings data and a PHP file named settings.php that contains a variable with a timestamp of the export. Is the settings.php file used for anything? I see there is a method in `WPV_PATH/embedded/inc/wpv-import-export-embedded.php` named `legacy_init` in the `WPV_Export_Import_Embedded` class that appears to use it.

**Comment by zaantar** [comment]
@baizmandesign After a short research, I believe that this `settings.php` file is somehow related to a very ancient mechanism of Layouts Embedded, where one could extract the core of the plugin (without the GUI to configure it) and insert it into their own theme and then ship it together with some pre-configured content. I don't think it will have any impact whatsoever on how Layouts works now.

**Comment by zaantar** [comment]
PR merged, closing here.
